# VirtualBox EDR Sample Analysis System Configuration File

# HTTP Server Configuration
server:
  host: "0.0.0.0"                    # Listen address
  port: 8000                         # Listen port
  api_key: "edr-analysis-2025"       # API key
  upload_dir: "./uploads"            # File upload directory
  max_file_size: 104857600          # Maximum file size (100MB)

# Virtualization Platform Configuration
virtualization:
  # VirtualBox Configuration (for Windows analysis)
  virtualbox:
    vboxmanage_path: "auto"          # VBoxManage path, auto for auto-detection
    vm_startup_mode: "gui"           # VM startup mode: "gui" or "headless"

  # QEMU Configuration (for Linux/Firmware analysis)
  qemu:
    # Default settings for all architectures
    default_memory: "512"            # Default memory allocation (MB)
    default_smp: "1"                 # Default CPU cores
    default_display: "vnc"           # Default display: "vnc", "gtk", "sdl"
    vnc_base_port: 5900             # VNC base port (display :0 = port 5900)
    vm_images_dir: "./vm_images"     # VM images directory

# Task Configuration
task_settings:
  default_analysis_timeout: 300  # Default analysis timeout (seconds) - further reduced to 180s (3 minutes)
  max_analysis_timeout: 1800     # Maximum analysis timeout (seconds)
  cleanup_after_analysis: true   # Whether to auto cleanup after analysis
  concurrent_tasks: 50           # Number of concurrent tasks - increased from 8 to 10
  max_queue_size: 100            # Maximum queue size

# Logging Configuration
logging:
  level: "DEBUG"                      # Log level (DEBUG, INFO, WARNING, ERROR)
  file: "./logs/vmm_edr.log"         # Log file path
  max_size: "10MB"                   # Maximum log file size
  backup_count: 5                    # Number of log files to keep

# Windows Analysis Configuration
windows:
  # EDR Sample Analysis Configuration
  edr_analysis:
    # Virtual Machine Configuration
    vms:
      - name: "win10-64-defender"
        antivirus: "defender"
        username: "vboxuser"
        password: "123456"
        baseline_snapshot: "edr-baseline"
        desktop_path: "C:\\Users\\vboxuser\\Desktop"


      - name: "win10-64-mcafee"
        antivirus: "mcafee"
        username: "vboxuser"
        password: "123456"
        baseline_snapshot: "edr-baseline"
        desktop_path: "C:\\Users\\vboxuser\\Desktop"

      - name: "win10-64-kaspersky"
        antivirus: "kaspersky"
        username: "vboxuser"
        password: "123456"
        baseline_snapshot: "edr-baseline"
        desktop_path: "C:\\Users\\vboxuser\\Desktop"

      - name: "win10-64-avira"
        antivirus: "avira"
        username: "vboxuser"
        password: "123456"
        baseline_snapshot: "edr-baseline"
        desktop_path: "C:\\Users\\vboxuser\\Desktop"

      - name: "win10-64-trend"
        antivirus: "trend"
        username: "vboxuser"
        password: "123456"
        baseline_snapshot: "edr-baseline"
        desktop_path: "C:\\Users\\vboxuser\\Desktop"


    # Analysis Configuration - Further optimized timing settings for performance improvement
    analysis_settings:
      initial_check_delay: 2            # Wait time after sample delivery for detection (seconds) - further reduced to 2s
      runtime_monitor_time: 60          # Monitor time after sample execution (seconds) - reduced from 90s to 60s
      vm_startup_timeout: 300           # VM startup timeout (seconds) - reduced from 600s to 300s (5 minutes)
      file_transfer_timeout: 10        # File transfer timeout (seconds)

    # Sample File Configuration
    sample_settings:
      max_sample_size: 52428800         # Maximum sample size (50MB)
      allowed_extensions: [".exe", ".dll", ".bat", ".ps1", ".vbs", ".jar", ".zip"]  # Allowed file extensions

  # Sysmon Analysis Configuration
  sysmon_analysis:
    # Whether to enable Sysmon analysis
    enabled: true

    # Sysmon dedicated virtual machine configuration
    vm:
      name: "win10-64-sysmon"
      antivirus: "defender"
      username: "vboxuser"
      password: "123456"
      baseline_snapshot: "edr-baseline"
      desktop_path: "C:\\Users\\vboxuser\\Desktop"

    # Sysmon configuration type
    config_type: "light"  # "light", "full", "custom"

    # Custom configuration file path (used when config_type is custom)
    custom_config_path: ""

    # Event collection configuration
    event_collection:
      max_events: 1000              # Maximum number of events collected per analysis
      collection_timeout: 30        # Event collection timeout (seconds)
      # Sysmon Event Type IDs to collect:
      # 1  - Process creation
      # 2  - File creation time changed
      # 3  - Network connection (TCP/UDP)
      # 4  - Sysmon service state changed
      # 5  - Process terminated
      # 6  - Driver loaded
      # 7  - Image loaded
      # 8  - CreateRemoteThread (Thread injection)
      # 9  - RawAccessRead (Raw disk access)
      # 10 - ProcessAccess (Process memory access)
      # 11 - FileCreate
      # 12 - RegistryEvent (Object create and delete)
      # 13 - RegistryEvent (Value Set) - includes startup entries
      # 14 - RegistryEvent (Key and Value Rename)
      # 15 - FileCreateStreamHash (NTFS stream created)
      # 16 - ServiceConfigurationChange (Service configuration change)
      # 17 - PipeEvent (Named pipe created)
      # 18 - PipeEvent (Named pipe connected)
      # 19 - WmiEvent (WMI filter)
      # 20 - WmiEvent (WMI consumer)
      # 21 - WmiEvent (WMI consumer filter)
      # 22 - DNSEvent (DNS query)
      # 23 - FileDelete (A file delete was detected)
      # 24 - ClipboardChange (New content in the clipboard)
      # 25 - ProcessTampering (Process image change)
      # 26 - FileDeleteDetected (File delete logged)
      # 27 - FileBlockExecutable (File block executable)
      # 28 - FileBlockShredding (File block shredding)
      event_types: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

    # Analysis configuration
    analysis_settings:
      pre_execution_delay: 3        # Wait time before sample execution (seconds) - reduced from 5s to 3s
      post_execution_delay: 45      # Wait time after sample execution (seconds) - reduced from 60s to 45s
      enable_process_tree: true     # Whether to build process tree
      enable_network_analysis: true # Whether to analyze network connections
      enable_file_analysis: true    # Whether to analyze file operations
      enable_registry_analysis: true # Whether to analyze registry operations

    # Output configuration
    output_settings:
      save_raw_events: true         # Whether to save raw event JSON
      save_analysis_report: true    # Whether to save analysis report
      output_format: "json"         # Output format: "json", "xml", "csv"

# Linux Behavioral Analysis Configuration
linux:
  # Behavioral analysis using QEMU
  behavioral_analysis:
    # Whether to enable Linux behavioral analysis
    enabled: true

    # Virtual Machine Configuration (using QEMU)
    vms:
      - name: "linux-x86_64"
        architecture: "x86_64"
        qemu_binary: "qemu-system-x86_64"
        machine: "pc-q35-6.2"
        cpu: "qemu64"
        acceleration: "tcg"          # "kvm" on Linux, "tcg" on Windows
        memory: "512"                # Memory in MB
        smp: "1"                     # CPU cores
        iso_file: "alpine-x86_64.iso"
        vnc_port: 5901
        description: "x86_64 Linux分析环境"

      - name: "linux-aarch64"
        architecture: "aarch64"
        qemu_binary: "qemu-system-aarch64"
        machine: "virt"
        cpu: "cortex-a72"
        acceleration: "tcg"
        memory: "512"
        smp: "1"
        iso_file: "alpine-arm64.iso"
        vnc_port: 5902
        description: "ARM64 IoT设备分析环境"

      - name: "linux-mips64"
        architecture: "mips64"
        qemu_binary: "qemu-system-mips64"
        machine: "malta"
        cpu: "MIPS64R2-generic"
        acceleration: "tcg"
        memory: "512"
        smp: "1"
        iso_file: "alpine-mips64.iso"
        vnc_port: 5903
        description: "MIPS64 路由器分析环境"

      - name: "linux-mips"
        architecture: "mips"
        qemu_binary: "qemu-system-mips"
        machine: "malta"
        cpu: "mips32r2-generic"
        acceleration: "tcg"
        memory: "512"
        smp: "1"
        iso_file: "alpine-mips.iso"
        vnc_port: 5904
        description: "MIPS32 嵌入式设备分析环境"

      - name: "linux-ppc64"
        architecture: "ppc64"
        qemu_binary: "qemu-system-ppc64"
        machine: "pseries"
        cpu: "power8"
        acceleration: "tcg"
        memory: "512"
        smp: "1"
        iso_file: "alpine-ppc64.iso"
        vnc_port: 5905
        description: "PowerPC64 服务器分析环境"

    # Analysis Configuration
    analysis_settings:
      # Timeout settings
      analysis_timeout: 300          # Analysis timeout (seconds)
      vm_startup_timeout: 120        # VM startup timeout (seconds)
      file_transfer_timeout: 30      # File transfer timeout (seconds)
      initial_check_delay: 5         # Wait time after sample delivery (seconds)
      runtime_monitor_time: 120      # Monitor time after sample execution (seconds)
      execution_timeout: 60          # Sample execution timeout (seconds)

    # Sample settings
    sample_settings:
      max_file_size: 104857600       # Maximum ELF file size (100MB)
      monitor_processes: true        # Monitor process creation
      monitor_network: true          # Monitor network connections
      monitor_files: true            # Monitor file operations
      capture_screenshots: false     # Capture VM screenshots

# Firmware Analysis Configuration
firmware:
  # Firmware analysis using QEMU emulation
  analysis:
    # Whether to enable firmware analysis
    enabled: true

    # Firmware analysis VMs (using QEMU)
    vms:
      - name: "firmware-arm"
        architecture: "arm"
        qemu_binary: "qemu-system-arm"
        machine: "versatilepb"
        cpu: "arm1176"
        acceleration: "tcg"
        memory: "256"
        smp: "1"
        description: "ARM固件分析环境"

      - name: "firmware-mips"
        architecture: "mips"
        qemu_binary: "qemu-system-mips"
        machine: "malta"
        cpu: "24Kf"
        acceleration: "tcg"
        memory: "256"
        smp: "1"
        description: "MIPS固件分析环境"

    # Firmware analysis settings
    analysis_settings:
      analysis_timeout: 600          # Firmware analysis timeout (10 minutes)
      emulation_timeout: 300         # Emulation timeout (5 minutes)
      enable_network_emulation: true # Enable network emulation
      enable_peripheral_emulation: true # Enable peripheral emulation

    # Firmware file settings
    firmware_settings:
      max_firmware_size: 536870912   # Maximum firmware size (512MB)
      supported_formats: ["bin", "img", "rom", "elf"]
      enable_extraction: true        # Enable firmware extraction
      enable_filesystem_analysis: true # Enable filesystem analysis
